CDPCP-13960 - Introduce schema and doc validation step for PRs

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -116,3 +116,25 @@ jobs:
           go-version-file: 'go.mod'
       - name: Run deadcode
         run: go install golang.org/x/tools/cmd/deadcode@latest && sh ./deadcode-check.sh
+  check-docs:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
+        with:
+          fetch-depth: 0
+      - name: Install Go
+        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
+        with:
+          go-version: 1.22
+      - name: Run documentation generation
+        run: |
+          make docs
+      - name: Check for changes in docs/
+        run: |
+          if git diff --exit-code docs; then
+            echo "No changes detected in docs/"
+          else
+            echo "Documentation is out of sync or invalid schema is present. Please run 'make docs' and commit the changes/fixes."
+            exit 1
+          fi
